server {
    listen 80;
    server_name _;
    root /var/www/daloradius/app/operators;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass php:9000;
        fastcgi_read_timeout 60s;
    }

    location ~* \.(css|js|jpg|jpeg|gif|png|svg|ico|woff|woff2|ttf)$ {
        expires 7d;
        access_log off;
    }
}

server {
    listen 81;
    server_name _;
    root /var/www/daloradius/app/users;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass php:9000;
        fastcgi_read_timeout 60s;
    }

    location ~* \.(css|js|jpg|jpeg|gif|png|svg|ico|woff|woff2|ttf)$ {
        expires 7d;
        access_log off;
    }
}
